import {Metadata} from "next"

export const metadata: Metadata = {
  title: {
    absolute:"",
    default:"Tutorial",
    template:"%s | Codevolution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header style={{backgroundColor: 'blue'}}><h1>Header</h1></header>
        {children}
        <footer style={{backgroundColor: 'red'}}><h2>Footer</h2></footer>
        </body>
    </html>
  )
}

