export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function ProductDetailsLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
          {children}
          <h1>Featured Products category</h1>
          <h4>Nested Layout</h4>
      </>
    )
  }
  